services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  react-app:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  meilisearch:
    image: 'getmeili/meilisearch:v1.14'
    ports:
      - '7700:7700'
    volumes:
      - './meili_data:/meili_data'
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=sup3rS3cur3Mast3rK3y!123 # This is ok for now...

volumes:
  postgres_data:
  meili_data: